"""RAG orchestration.

`answer_question()` retrieves the most relevant chunks for a question, then:
  • DEMO (default, keyless): assembles a clearly-labelled EXTRACTIVE answer from
    the best-matching sentences in those chunks — no LLM, no network. The answer
    is literally quoted from your documents, with citations.
  • FULL (only if an API key is set): sends the retrieved context + question to
    an LLM for a natural-language answer, still returning the same citations.
"""
import re

from . import config, llm, store
from .index import tokenize

_SENT_SPLIT = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9])")


def _sentences(text: str) -> list[str]:
    parts = [s.strip() for s in _SENT_SPLIT.split(text) if s.strip()]
    return parts or ([text.strip()] if text.strip() else [])


def _snippet(text: str, limit: int = 240) -> str:
    text = text.strip()
    return text if len(text) <= limit else text[:limit].rsplit(" ", 1)[0] + "…"


def _extractive_answer(question: str, hits: list[dict]) -> str:
    """Pick the best-matching sentences across the retrieved chunks."""
    q_terms = set(tokenize(question))
    scored: list[tuple[float, int, str]] = []
    for rank, hit in enumerate(hits):
        for sent in _sentences(hit["text"]):
            s_terms = tokenize(sent)
            if not s_terms:
                continue
            overlap = sum(1 for t in s_terms if t in q_terms)
            if overlap == 0:
                continue
            # Favour sentences that cover more query terms; tie-break on the
            # chunk's retrieval rank, then prefer shorter, denser sentences.
            density = overlap / len(s_terms)
            score = overlap + density - 0.01 * rank
            scored.append((score, len(sent), sent))
    if not scored:
        # No sentence overlapped — fall back to the top chunk's opening.
        return _snippet(hits[0]["text"])
    scored.sort(key=lambda x: (-x[0], x[1]))
    chosen: list[str] = []
    seen = set()
    for _, _, sent in scored:
        key = sent.lower()
        if key in seen:
            continue
        seen.add(key)
        chosen.append(sent)
        if len(chosen) >= 3:
            break
    return " ".join(chosen)


def _citations(hits: list[dict]) -> list[dict]:
    return [
        {
            "doc_id": h["doc_id"],
            "document": h["doc_name"],
            "page": h["page"],
            "chunk": h["chunk_index"],
            "score": h["score"],
            "snippet": _snippet(h["text"]),
        }
        for h in hits
    ]


def answer_question(question: str, top_k: int | None = None) -> dict:
    question = (question or "").strip()
    if not question:
        return {"mode": "demo", "answer": "Please type a question.", "citations": []}

    hits = store.search(question, top_k=top_k or config.TOP_K)
    if not hits:
        return {
            "mode": "demo",
            "answer": "I couldn't find anything relevant in the indexed documents "
                      "for that question. Try rephrasing, or ask about the sample "
                      "documents (handbook, product manual, refund policy).",
            "citations": [],
            "label": _LABEL_DEMO,
        }

    citations = _citations(hits)

    if config.LLM_ENABLED:
        provider = config.llm_provider()
        text = llm.generate_answer(question, hits)
        return {
            "mode": "llm",
            "provider": provider,
            "answer": text,
            "citations": citations,
            "label": f"AI answer — generated by {provider} from the retrieved context.",
        }

    return {
        "mode": "demo",
        "answer": _extractive_answer(question, hits),
        "citations": citations,
        "label": _LABEL_DEMO,
    }


_LABEL_DEMO = "Demo answer — retrieved from your documents, no LLM generation."
